// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import ModalWrapper from "../components/ModalWrapper";
import TopLoader from "../components/shared/TopLoader";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Shop For You",
  description: "Next Shop Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <TopLoader color="#f1a10d" />
      <Header />
      <ModalWrapper />
      <main>{children}</main>
      <Footer />
    </>
  );
}
