import Header from "../components/admin/Header";
import Sidebar from "../components/admin/Sidebar";
import TopLoader from "../components/shared/TopLoader";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Admin Panel",
    description: "Next Shop Generated by create next app",
};

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex h-screen overflow-hidden">
      <Sidebar />
      <TopLoader color="oklch(21% 0.034 264.665)"/>
      <div className="flex flex-col flex-1">
        <Header />
        <main className="flex-1 overflow-y-auto bg-gray-50 p-4">
          {children}
        </main>
      </div>
    </div>
  );
}
